### ISSUE TITLE
Register User Activity

### ISSUE THREAD

**Issue by insanecoder02** [opencodeiiita/Text-It#83] opened 2023-12-15 10:48 UTC
Create a **Register Activity** asking the user its :- 
- name
- email
- password
- confirm password

Ensure a visually appealing design to enhance user experience. 🎨

_Happy contributing! 😊_

**Comment by Apoorv012** [comment] 2023-12-15 10:49
claim

**Comment by CodinJack** [comment] 2023-12-15 10:50
claim

**Comment by Murdock9803** [comment] 2023-12-15 10:50
Claim

**Comment by kushal7201** [comment] 2023-12-15 10:50
claim

**Comment by vasusingla545** [comment] 2023-12-15 10:50
ckaim

**Comment by AngadManroy** [comment] 2023-12-15 10:50
claim

**Comment by Reene-Simon** [comment] 2023-12-15 10:51
claim

**Comment by insanecoder02** [comment] 2023-12-15 10:51
assigned to @Apoorv012

**Comment by Nandinig24** [comment] 2023-12-15 10:52
Claim

**Comment by divyanshrai03** [comment] 2023-12-15 10:52
claim

**Comment by sanjayh-2022** [comment] 2023-12-15 10:57
Claim

**Comment by Apoorv012** [comment] 2023-12-15 17:19
Sorry, could you please unassign me.

**Comment by muffinboy19** [comment] 2023-12-15 18:33
comment from here will be considered

**Comment by chiragmalik2612** [comment] 2023-12-15 18:37
claim

**Comment by CodinJack** [comment] 2023-12-15 18:38
claim

**Comment by muffinboy19** [comment] 2023-12-15 20:58
@chiragmalik2612  is reassigned the issue

**Comment by chiragmalik2612** [comment] 2023-12-16 06:32
@muffinboy19 where to make pull request / show design.

**Comment by insanecoder02** [comment] 2023-12-16 06:39
You have to create a new activity for register user and attach the png of your work in PR

**Comment by muffinboy19** [comment] 2023-12-16 09:40
The issue is reassgined to @CodinJack

**Closed** 2023-12-16 14:35 UTC
Labels: Points: 10, good first issue, xml
